# Nome do seu workflow. Aparecerá na aba "Actions" do seu repositório.
name: CI para Projeto Node.js

# Gatilho (trigger): define quando o workflow deve ser executado.
on:
  # Executa em todo 'push' para a branch 'main'.
  push:
    branches: [ main ]
  # Também executa em 'pull requests' abertos para a branch 'main'.
  pull_request:
    branches: [ main ]

# Jobs: define as tarefas que serão executadas
jobs:
  # 'build' é o ID do nosso job. Você pode nomeá-lo como quiser.
  build:
    # Define o sistema operacional da máquina virtual que executará o job.
    runs-on: ubuntu-latest

    # Passos (steps) a serem executados sequencialmente.
    steps:
      # Passo 1: Baixa o seu código do repositório para a máquina virtual.
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configura a versão do Node.js que queremos usar.
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Você pode especificar a versão que seu projeto usa.
          cache: 'npm' # Opcional: acelera a instalação de dependências em execuções futuras.

      # Passo 3: Instala as dependências do projeto.
      - name: Instalar dependências
        run: npm install

      # Passo 4: Executa o script de teste definido no package.json.
      - name: Rodar os testes
        run: npm test