# Nome do seu workflow. Aparecerá na aba "Actions" do seu repositório.
name: CI para Projeto Node.js com SonarCloud

# Gatilho (trigger): define quando o workflow deve ser executado.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          # Faz o fetch de todo o histórico para que o Sonar possa fazer uma análise mais completa
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar os testes
        run: npm test

      # --- NOVO PASSO ADICIONADO AQUI ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          # Token de acesso para o SonarCloud, armazenado nos Secrets do GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Estes valores são encontrados na página do seu projeto no SonarCloud
          # Vá em "Project Information" para encontrá-los
          args: >
            -Dsonar.projectKey=brenoveroneze_meu-primeiro-ci-cd
            -Dsonar.organization=brenoveroneze